[project]
name = "azure-ml-deployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.09"
dependencies = [
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "xgboost>=2.1.4",
]
